version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  maven: circleci/maven@1.4

workflows:
  build-and-test:
    jobs:
      - checkstyle
      - test-java
      - publish-docs:
          requires:
            - test-java

jobs:
  checkstyle:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          command: mvn verify
      - run:
          command: mvn test
      - run:
          name: Jacoco report generation
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - store_artifacts:
          path: target/site/jacoco/jacoco.xml
          destination: jacoco
  publish-docs:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Add GitHub to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            # Configurer git pour publier sur GitHub Pages
            git config user.name "noobmaster122"
            git config user.email "brahimi.a.farouk@gmail.com"
            git clone --branch gh-pages git@github.com:noobmaster122/ceri-m1-techniques-de-test.git gh-pages
            rm -rf gh-pages/*
            cp -r target/site/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "Update Javadoc [skip ci]"
            git push origin gh-pages