version: 2.1

orbs:
  codecov: codecov/codecov@5
  maven: circleci/maven@1.4

workflows:
  build-and-test:
    jobs:
      - test-java

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
#      - run:
#          name: Calculate cache key
#          command: |-
#            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
#                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
#      - restore_cache:
#          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify
      - run:
          command: mvn test
      - run:
          name: Jacoco report generation
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml