version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1
  maven: circleci/maven@1.4

workflows:
  build-and-test:
    jobs:
      - checkstyle
      - test-java

jobs:
  checkstyle:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          command: mvn verify
      - run:
          command: mvn test
      - run:
          name: Jacoco report generation
          command: mvn jacoco:report
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
      - store_artifacts:
          path: target/site/jacoco/jacoco.xml
          destination: jacoco